apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: garaxe-local-static
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: garaxe-postgres-data
  labels:
    storage.garaxe.dev/volume: postgres
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: garaxe-local-static
  hostPath:
    path: /var/lib/garaxe/postgres
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["ubuntu"]
