export type Blinded100InputItem = { id: string; text: string; sourceUrl: string }

// Consent-safe synthetic public-style feedback. This file contains no gold
// category, topic, or merge labels and is the only fixture sent to the model.
const texts = [
  'The invoice total includes an unexplained regional tax line, so I cannot reconcile the final amount.',
  'Project search disappears from the mobile header after I scroll into a long workspace.',
  'The PDF report export stalls near completion and never produces the download.',
  'Support repeated the documentation but did not explain how to repair the failed import.',
  'Please show compile and upload progress so I can tell whether the board is still moving.',
  'I want a guided setup path that makes the next configuration step obvious.',
  'Please pair every status color with text so the state remains understandable without color.',
  'I want to keep editing a draft offline and sync it after the connection returns.',
  'I am hesitant to migrate because historical customer notes might disappear.',
  'I would not sign an annual agreement without a clear cancellation window.',
  'I would not adopt remote workspaces if the app can write locally without explicit permission.',
  'I am unsure whether the trial price increases when a second analyst joins.',
  'I feel anxious when saving finishes without any confirmation that my changes were kept.',
  'I feel frustrated when a terminal command freezes without a response or error.',
  'I am afraid a workspace deletion will remove the wrong data because there is no preview.',
  'I felt relieved when the delayed refund finally returned to my account.',
  'What does the documented thirty-day retention period cover after a project is archived?',
  'Which subscription tier includes single sign-on according to the current plan comparison?',
  'In the documentation, what does the term pinned session mean?',
  'Which legal entity is listed as the processor for European workspace data?',
  'An unexpected tax adjustment changes the invoice after checkout and the calculation is not explained.',
  'On a phone, the search control is hidden inside navigation while the project list remains visible.',
  'Exporting a large report hangs at the last step instead of returning a PDF file.',
  'The support answer linked to a guide but never identified the step that would fix the broken upload.',
  'A visible build progress indicator would show whether firmware compilation is active or stuck.',
  'Please make onboarding show the completed milestone and the next action during initial setup.',
  'Status chips need written labels in addition to red, amber, and green fills.',
  'Draft changes should remain editable without a network connection and synchronize later.',
  'Before switching tools, I need assurance that account history survives the migration.',
  'A twelve-month contract is a blocker unless the renewal and exit terms are explicit.',
  'Remote development is unacceptable if background tasks can modify files on my laptop without consent.',
  'Before inviting another teammate, I need to know how that changes trial pricing.',
  'A silent save makes me nervous that the document may not have been stored.',
  'When a command sits silently for half an hour, I become frustrated and do not know whether it is alive.',
  'Deleting a workspace without seeing the affected records makes me fearful of an irreversible mistake.',
  'The refund notification was a relief after weeks of waiting for the money to arrive.',
  'Does retention start when an item is deleted, archived, or when the workspace closes?',
  'Is audit-log access part of the Business tier or only the Enterprise tier?',
  'What is the documented difference between a workspace scope and a project scope?',
  'Does the compliance page name a separate subprocessor for files stored in Canada?',
  'The final bill applies tax twice to the same line item and gives no reason for the duplicate charge.',
  'Mobile navigation removes the project search field exactly when the list becomes long enough to need it.',
  'A report remains at ninety-two percent during export and the PDF is never completed.',
  'The reply from support described the symptom but omitted the recovery procedure for the import error.',
  'I need separate progress for compiling and uploading rather than discovering a timeout after both stall.',
  'A step-by-step onboarding checklist would let me finish configuration without guessing.',
  'Color-only labels make warning and success states indistinguishable for me.',
  'Let me write and organize draft notes offline, then merge them when connectivity resumes.',
  'The possibility of losing saved conversations keeps me from moving to the new platform.',
  'I will not commit to the yearly plan while cancellation timing remains ambiguous.',
  'Local file access from a remote session is an adoption barrier unless each write is approved.',
  'The trial terms do not say whether adding an analyst changes the monthly price.',
  'I worry that my work vanished whenever the save control gives no visible acknowledgement.',
  'A frozen shell with no output makes me angry because there is no way to tell if the task continues.',
  'I feel scared to confirm deletion when the product does not show which workspace content will disappear.',
  'Seeing the repayment land brought relief, although the refund had taken much longer than expected.',
  'When the policy says retained backup, does that include exported reports or only source feedback?',
  'Which plan currently includes custom roles and permission groups?',
  'What does canonical project mean in the import reference?',
  'Which regions are covered by the published data-processing addendum?',
  'Tax appears only after payment and makes the invoice total differ from the quoted amount.',
  'I cannot reach project search from the mobile header without opening and closing several menus.',
  'Generating the evidence report stops before the PDF download link appears.',
  'Support closed the ticket with a generic answer that did not resolve the failing synchronization.',
  'Show a live upload stage and estimated progress while the build artifact is transferred.',
  'I want setup to explain why each onboarding step is required before I continue.',
  'Add text or icons to colored status markers so their meaning is not dependent on hue.',
  'Offline draft support would let field staff record notes before they regain service.',
  'I cannot approve a migration until I know historical notes and attachments will remain intact.',
  'Without a straightforward exit clause, the annual subscription feels too risky to accept.',
  'The remote agent must ask before writing to local directories or I will not enable it.',
  'I hesitate to add collaborators during the trial because the future price is unclear.',
  'No save confirmation leaves me anxious that closing the page will lose recent edits.',
  'I get frustrated when a long-running command provides neither progress nor a failure message.',
  'A one-click delete action makes me afraid because it offers no review of the selected workspace.',
  'I was relieved to see the refund completed and the original payment restored.',
  'Is an archived project removed automatically when its retention window ends?',
  'Does the Team plan include report scheduling in the published feature table?',
  'How does the glossary define an immutable report revision?',
  'Who is identified as the data controller for accounts billed from Australia?',
  'Invoice tax is calculated differently from the checkout estimate, leaving the final charge hard to verify.',
  'The compact mobile menu buries search even though finding a project is the main reason I opened it.',
  'Report export spins indefinitely after charts render and no PDF is delivered.',
  'The support response did not include a concrete fix for restoring the corrupted configuration.',
  'Please display build and upload stages with progress instead of one silent loading state.',
  'A guided onboarding sequence with clear milestones would make first-time setup easier to complete.',
  'Every colored severity badge should include a readable status name.',
  'I want drafts to save locally while offline and synchronize safely when the device reconnects.',
  'I am reluctant to switch because the migration documentation does not guarantee preservation of history.',
  'I would reject the yearly contract unless cancellation and renewal dates are stated before purchase.',
  'I cannot trust remote mode while it may change local files without a permission prompt.',
  'Unclear pricing after the trial prevents me from inviting the rest of the team.',
  'I feel nervous when the editor says nothing after I press save.',
  'A command that freezes without status or output makes me deeply frustrated.',
  'I fear deleting important records because the workspace removal flow has no preview.',
  'The completed refund made me feel relieved after the earlier delay.',
  'What is the retention rule for generated reports after their source project is deleted?',
  'According to the pricing page, which tier permits more than ten reviewers?',
  'What does source authority mean in the synchronization guide?',
  'Does the security statement specify where United States backups are processed?',
]

export const blinded100Input: Blinded100InputItem[] = texts.map((text, index) => ({
  id: `blind-${String(index + 1).padStart(3, '0')}`,
  text,
  sourceUrl: `https://example.invalid/public-feedback/${String(index + 1).padStart(3, '0')}`,
}))
