apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garaxe
resources:
  - ../../../base/app
images:
  - name: ghcr.io/cutedandelion/garaxe-api
    newTag: "REPLACE_WITH_GIT_SHA"
  - name: ghcr.io/cutedandelion/garaxe-web
    newTag: "REPLACE_WITH_GIT_SHA"
